applynsubmit/urls.py
from django.urls import path
from .views import *

app_name = "applynsubmit"
urlpatterns = [
    path("applymembership", applymembership, name="applymembership"),
    path(
        "applymembershipwithdrawal",
        applymembershipwithdrawal,
        name="applymembershipwithdrawal",
    ),
    path(
        "applymembership/cron-delete-all-expired-recruiting-data",
        cron_delete_all_expired_recruiting_data,
        name="cron_delete_all_expired_recruiting_data",
    ),
    path(
        "applymembershipwithdrawal/cron-delete-queued-alumni-data",
        cron_delete_queued_alumni_data,
        name="cron_delete_queued_alumni_data",
    ),
]

bluemoveportal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("home.urls")),
    path("checknissue/", include("checknissue.urls")),
    path("applynsubmit/", include("applynsubmit.urls")),
    path("decidenshare/", include("decidenshare.urls")),
    path("draftnapprove/", include("draftnapprove.urls")),
    path("member/", include("member.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

checknissue/urls.py
from django.urls import path
from .views import *

app_name = "checknissue"
urlpatterns = [
    path("checklist", checklist, name="checklist"),
    path("checkcert", checkcert, name="checkcert"),
    path("issuecert", issuecert, name="issuecert"),
]

decidenshare/urls.py
from django.urls import path
from .views import *

app_name = "decidenshare"
urlpatterns = [
    path("sharebmlink", sharebmlink, name="sharebmlink"),
    path("sharebmlink/cron-delete-all-expired-bmlinks", cron_delete_all_expired_bmlinks, name="cron_delete_all_expired_bmlinks"),
]

draftnapprove/urls.py
from django.urls import path
from .views import *

app_name = "draftnapprove"
urlpatterns = [
    path("activityreport", activityreport, name="activityreport"),
    path("activityreport/cron-remind-approvers-about-all-activity-reports-in-the-queue", cron_remind_approvers_about_all_activity_reports_in_the_queue, name="cron_remind_approvers_about_all_activity_reports_in_the_queue"),
    path("activityreport/cron-notify-about-tasks-done", cron_notify_about_tasks_done, name="cron_notify_about_tasks_done"),
    path("activityreport/cron-notify-about-tasks-to-be-done", cron_notify_about_tasks_to_be_done, name="cron_notify_about_tasks_to_be_done"),
    path("activityreport/cron-notify-about-msg", cron_notify_about_msg, name="cron_notify_about_msg"),
    path("activityreport/get-google-token/", get_google_token, name="get_google_token"),
]

home/urls.py
from django.urls import path
from .views import *

app_name = "home"
urlpatterns = [
    path("", main, name="main"),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, redirect


####
#### views
####
def main(request):
    return render(request, "home/main.html")

home/templates/home/main.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
<meta property="og:url" content="{% url 'home:main' %}">
<meta property="og:title" content="블루무브 포털">
<meta property="og:description" content="파란물결 블루무브 종합정보시스템 '블루무브 포털'">
<meta name="subject" content="파란물결 블루무브 종합정보시스템 '블루무브 포털'">
<meta name="description" content="파란물결 블루무브 종합정보시스템 '블루무브 포털'">
<meta name="robots" content="index,follow">
{% endblock %}

{% block title %} 블루무브 포털 {% endblock %}

{% block banner %}
<!--
---- banner large (1800x450)
-->
<div id="mainCarousel" class="screenLarge carousel slide pointer-event" data-bs-ride="carousel">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#mainCarousel" data-bs-slide-to="0" aria-label="Slide 1"
            class=""></button>
        <button type="button" data-bs-target="#mainCarousel" data-bs-slide-to="1" aria-label="Slide 2" class="active"
            aria-current="true"></button>
        <button type="button" data-bs-target="#mainCarousel" data-bs-slide-to="2" aria-label="Slide 3"
            class=""></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item">
            <img src="{% static 'images/1800x450Default.png' %}" class="lozad d-block w-100">
        </div>
        <div class="carousel-item active">
            <img src="{% static 'images/1800x450Default.png' %}" class="lozad d-block w-100">
        </div>
        <div class="carousel-item">
            <img src="{% static 'images/1800x450Default.png' %}" class="lozad d-block w-100">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#mainCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#mainCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

<!--
---- banner small (900x450)
-->
<div id="mainCarousel" class="screenSmall carousel slide pointer-event" data-bs-ride="carousel">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#mainCarousel" data-bs-slide-to="0" aria-label="Slide 1"
            class=""></button>
        <button type="button" data-bs-target="#mainCarousel" data-bs-slide-to="1" aria-label="Slide 2" class="active"
            aria-current="true"></button>
        <button type="button" data-bs-target="#mainCarousel" data-bs-slide-to="2" aria-label="Slide 3"
            class=""></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item">
            <img src="{% static 'images/1800x900Default.png' %}" class="lozad d-block w-100">
        </div>
        <div class="carousel-item active">
            <img src="{% static 'images/1800x900Default.png' %}" class="lozad d-block w-100">
        </div>
        <div class="carousel-item">
            <img src="{% static 'images/1800x900Default.png' %}" class="lozad d-block w-100">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#mainCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#mainCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>
{% endblock %}

{% block content %}
<!--
---- inner contents
-->
<div class="alert alert-primary d-flex align-items-center" role="alert">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
        class="bi bi-cone-striped flex-shrink-0 me-2" viewBox="0 0 16 16">
        <path
            d="m9.97 4.88.953 3.811C10.159 8.878 9.14 9 8 9c-1.14 0-2.158-.122-2.923-.309L6.03 4.88C6.635 4.957 7.3 5 8 5s1.365-.043 1.97-.12zm-.245-.978L8.97.88C8.718-.13 7.282-.13 7.03.88L6.275 3.9C6.8 3.965 7.382 4 8 4c.618 0 1.2-.036 1.725-.098zm4.396 8.613a.5.5 0 0 1 .037.96l-6 2a.5.5 0 0 1-.316 0l-6-2a.5.5 0 0 1 .037-.96l2.391-.598.565-2.257c.862.212 1.964.339 3.165.339s2.303-.127 3.165-.339l.565 2.257 2.391.598z" />
    </svg>
    <div class="vertical">
        <p class="m-0 mb-1">현재는 다음 서비스만 이용하실 수 있습니다.</p>
        <small>
            <span class="badge badge-bluemove bg-secondary me-1">조회/발급</span>
            <a href="{% url 'checknissue:checklist' %}" class="a-bluemove vertical"
                onclick="fadeOut(); setTimeout(inProgress, 0);">블루무버 명단 조회</a>,
            <a href="{% url 'checknissue:checkcert' %}" class="a-bluemove vertical"
                onclick="fadeOut(); setTimeout(inProgress, 0);">활동증명서 진위 확인</a>,
            <a href="{% url 'checknissue:issuecert' %}" class="a-bluemove vertical"
                onclick="fadeOut(); setTimeout(inProgress, 0);">활동증명서 발급</a>
            <br>
            <span class="badge badge-bluemove bg-secondary me-1">신청/제출</span>
            <a href="{% url 'applynsubmit:applymembership' %}" class="a-bluemove vertical"
                onclick="fadeOut(); setTimeout(inProgress, 0);">블루무브 가입 지원</a>,
            <a href="{% url 'applynsubmit:applymembershipwithdrawal' %}" class="a-bluemove vertical"
                onclick="fadeOut(); setTimeout(inProgress, 0);">블루무브 탈퇴 신청</a>
            <br>
            <span class="badge badge-bluemove bg-secondary me-1">의결/공유</span>
            <a href="{% url 'decidenshare:sharebmlink' %}" class="a-bluemove vertical"
                onclick="fadeOut(); setTimeout(inProgress, 0);">블뭅링크 공유</a>
            <br>
            <span class="badge badge-bluemove bg-secondary me-1">기안/결재</span>
            <a href="{% url 'draftnapprove:activityreport' %}" class="a-bluemove vertical"
                onclick="fadeOut(); setTimeout(inProgress, 0);">일일활동보고서</a>
        </small>
    </div>
</div>
<div class="alert alert-secondary d-flex align-items-center mb-0" role="alert">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
        class="bi bi-info-circle flex-shrink-0 me-2" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
        <path
            d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0z" />
    </svg>
    <div class="vertical">
        문의 사항이 있으실 경우 <a href="mailto:management@bluemove.or.kr" class="a-bluemove">management@bluemove.or.kr</a>로 연락
        부탁드립니다.
    </div>
</div>
{% endblock %}